"""
screener/lib/storage/schema.py — Collection constants, doc-ID builders, and
Pydantic document schemas for the multi-agent stock screener.

Collection layout (mirrors the private reference implementation):

    tickers/                              — per-ticker signal data
    tickers/{SYMBOL}/memory/{MONTH_ID}    — per-ticker episodic memory (subcollection)
    signals/     — monthly raw signal snapshots written by financial_update_job
    picks/       — monthly screener top-N snapshots (screener_picks)
    performance/ — monthly P&L snapshots and pick ledger
    chunks/      — EDGAR 10-K/10-Q text chunks with vector embeddings (disclosure_chunks)
    eval/        — monthly eval output (evals_output)
    events/      — pipeline lifecycle events (screener_events)

Doc ID conventions:
    - screening_{YYYYMMDD}              → tickers
    - {TICKER}_{YYYY-MM}                → signals docs (e.g. "AAPL_2026-04")
    - picks_{YYYYWW}                    → picks snapshot (legacy; not used in write path)
    - perf_{YYYYWW}                     → performance snapshots
    - {TICKER}_{YYYY-MM}_{source}       → pick ledger entries (e.g. "AAPL_2026-04_judge")
    - {MONTH_ID}                        → memory docs (e.g. "2026-04", one per month per ticker)
    - chunk_{TICKER_SLUG}_{IDX}         → EDGAR chunks
    - eval_{YYYYMM}                     → eval docs
    - event_{UUID}                      → event docs (auto-generated by Firestore)

Memory subcollection path helper:
    memory_collection_path(ticker)  → "tickers/AAPL/memory"
    memory_doc_id(month_id)         → "2026-04"
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Collection name constants
# ---------------------------------------------------------------------------

TICKERS: str = "tickers"
MEMORY: str = "memory"
SIGNALS: str = "signals"
PICKS: str = "picks"
PERFORMANCE: str = "performance"
CHUNKS: str = "chunks"
EVAL: str = "eval"
EVENTS: str = "events"


# ---------------------------------------------------------------------------
# Doc ID helper functions
# ---------------------------------------------------------------------------


def ticker_to_slug(ticker: str) -> str:
    """Canonical slug used in Firestore doc IDs.

    Lower-cases the ticker and replaces ``-`` and ``.`` with ``_`` so that
    symbols like ``BRK.B`` and ``BF-B`` produce valid, predictable IDs.

    Examples::

        ticker_to_slug("AAPL")   → "aapl"
        ticker_to_slug("BRK.B")  → "brk_b"
        ticker_to_slug("BF-B")   → "bf_b"
    """
    return ticker.lower().replace("-", "_").replace(".", "_")


def screening_doc_id(date_str: str) -> str:
    """Doc ID for a daily ticker-signals snapshot.

    Args:
        date_str: ISO date string, e.g. ``"2026-04-29"``.

    Returns:
        e.g. ``"screening_20260429"``
    """
    return f"screening_{date_str.replace('-', '')}"


def picks_doc_id(week_id: str) -> str:
    """Doc ID for a weekly picks snapshot.

    Args:
        week_id: ISO week string, e.g. ``"202618"``.

    Returns:
        e.g. ``"picks_202618"``
    """
    return f"picks_{week_id}"


def perf_snapshot_doc_id(week_id: str) -> str:
    """Doc ID for a weekly performance snapshot.

    Args:
        week_id: ISO week string, e.g. ``"202618"``.

    Returns:
        e.g. ``"perf_202618"``
    """
    return f"perf_{week_id}"


def pick_ledger_doc_id(ticker: str, month_id: str, source: str = "judge") -> str:
    """Doc ID for an individual pick-ledger entry in the ``picks`` collection.

    Args:
        ticker: Upper-case ticker symbol, e.g. ``"AAPL"``.
        month_id: Month identifier in ``"YYYY-MM"`` format, e.g. ``"2026-04"``.
        source: Agent that produced the verdict; defaults to ``"judge"``.

    Returns:
        e.g. ``"AAPL_2026-04_judge"``
    """
    return f"{ticker.upper()}_{month_id}_{source}"


def memory_collection_path(ticker: str) -> str:
    """Firestore path for a ticker's episodic memory subcollection.

    The memory subcollection lives under the ticker's top-level document:
    ``tickers/{SYMBOL}/memory``.  Pass this as the ``collection`` argument
    to :meth:`StorageDAO.get` / :meth:`StorageDAO.set`.

    Args:
        ticker: Ticker symbol (any case).

    Returns:
        e.g. ``"tickers/AAPL/memory"``
    """
    return f"{TICKERS}/{ticker.upper()}/{MEMORY}"


def memory_doc_id(month_id: str) -> str:
    """Doc ID for a monthly episodic memory document.

    One document per month per ticker, keyed by ``YYYY-MM`` month identifier.
    The document lives at ``tickers/{SYMBOL}/memory/{MONTH_ID}``.

    Args:
        month_id: Month identifier in ``"YYYY-MM"`` format, e.g. ``"2026-04"``.

    Returns:
        The month_id unchanged, e.g. ``"2026-04"``
    """
    return month_id


def signal_doc_id(ticker: str, month_id: str) -> str:
    """Doc ID for a monthly raw-signal snapshot in the ``signals`` collection.

    Args:
        ticker: Upper-case ticker symbol, e.g. ``"AAPL"``.
        month_id: Month identifier in ``"YYYY-MM"`` format, e.g. ``"2026-04"``.

    Returns:
        e.g. ``"AAPL_2026-04"``
    """
    return f"{ticker.upper()}_{month_id}"


def current_month_id(dt: datetime | None = None) -> str:
    """Return the month ID string for a datetime, e.g. ``"2026-04"``.

    Args:
        dt: Datetime to use; defaults to ``datetime.now(timezone.utc)``.
    """
    if dt is None:
        dt = datetime.now(timezone.utc)
    return dt.strftime("%Y-%m")


def chunk_doc_id(ticker: str, index: int) -> str:
    """Doc ID for an EDGAR text chunk.

    Args:
        ticker: Ticker symbol (any case).
        index: Zero-based chunk index within the filing.

    Returns:
        e.g. ``"aapl_42"``
    """
    return f"{ticker_to_slug(ticker)}_{index}"


def eval_doc_id(year: int, month: int) -> str:
    """Doc ID for a monthly eval output document.

    Args:
        year: Four-digit year.
        month: Month number (1–12).

    Returns:
        e.g. ``"eval_202604"``
    """
    return f"eval_{year:04d}{month:02d}"


def current_week_id(dt: datetime | None = None) -> str:
    """Return the ISO week ID string for a datetime, e.g. ``"202618"``.

    Args:
        dt: Datetime to use; defaults to ``datetime.now(timezone.utc)``.
    """
    if dt is None:
        dt = datetime.now(timezone.utc)
    return dt.strftime("%G%V")


def current_quarter_id(dt: datetime | None = None) -> str:
    """Return the quarter ID string for a datetime, e.g. ``"2026Q2"``.

    Args:
        dt: Datetime to use; defaults to ``datetime.now(timezone.utc)``.
    """
    if dt is None:
        dt = datetime.now(timezone.utc)
    q = (dt.month - 1) // 3 + 1
    return f"{dt.year}Q{q}"


# ---------------------------------------------------------------------------
# Pydantic document schemas
# ---------------------------------------------------------------------------


class TickerSignalDoc(BaseModel):
    """Schema for a document in the ``tickers`` collection.

    Stores the most recent composite signal data for a single ticker.
    """

    symbol: str
    screening_date: str
    technical: float
    earnings: float
    fcf: float
    ebitda: float
    composite_score: float
    sector: str
    price: Optional[float] = None
    above_ma200: Optional[bool] = None


class SignalDoc(BaseModel):
    """Schema for a document in the ``signals`` collection.

    Written by ``financial_update_job`` after fetching earnings, FCF, and
    EBITDA signals for a single ticker.  One document per ticker per month.

    Doc ID: ``{TICKER}_{MONTH_ID}`` (e.g. ``"AAPL_2026-04"``).
    Firestore path: ``signals/AAPL_2026-04``.

    The ``set()`` DAO method is used for writes, which is idempotent (upsert):
    re-running the job for the same month safely overwrites the document.
    """

    ticker: str
    month_id: str
    fetched_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    earnings_yield: Optional[float] = None
    trailing_eps: Optional[float] = None
    price: Optional[float] = None
    earnings_skipped: bool = False
    earnings_skip_reason: Optional[str] = None
    fcf_yield: Optional[float] = None
    free_cashflow: Optional[float] = None
    market_cap: Optional[float] = None
    fcf_skipped: bool = False
    fcf_skip_reason: Optional[str] = None
    ebitda_ev: Optional[float] = None
    ebitda: Optional[float] = None
    enterprise_value: Optional[float] = None
    ebitda_skipped: bool = False
    ebitda_skip_reason: Optional[str] = None


class ScoringWeights(BaseModel):
    bull_weight: float = 0.5
    bear_weight: float = 0.5
    sample_size: int = 0


class MonthVerdict(BaseModel):
    action: str
    confidence: float
    horizon: Optional[str] = None
    winning_side: Optional[str] = None
    entry_price: Optional[float] = None
    direction_correct: Optional[bool] = None
    magnitude_error: Optional[float] = None
    scored_at: Optional[datetime] = None
    judge_signal_citations: list[str] = Field(default_factory=list)


class MemoryDoc(BaseModel):
    """Schema for a document in the ``tickers/{SYMBOL}/memory`` subcollection.

    One document per month per ticker.  The document ID is the month identifier
    (e.g. ``"2026-04"``).  The full Firestore path is:
    ``tickers/{SYMBOL}/memory/{MONTH_ID}``.
    """

    ticker: str
    month_id: str
    scoring_weights: ScoringWeights = Field(default_factory=ScoringWeights)
    verdict: Optional[MonthVerdict] = None


class PickEntry(BaseModel):
    rank: int
    symbol: str
    sector: str
    entry_price: float
    score: float


class PicksDoc(BaseModel):
    """Schema for a document in the ``picks`` collection.

    Monthly snapshot of the screener's top-N selections.
    """

    date: str
    month_id: str
    picks: list[PickEntry] = Field(default_factory=list)


class PickLedgerDoc(BaseModel):
    """Schema for an individual pick-ledger entry in the ``picks`` collection.

    Doc ID: ``{TICKER}_{MONTH_ID}_{source}`` (e.g. ``"AAPL_2026-04_judge"``).
    """

    ticker: str
    source: str = "judge"
    entry_month: str
    entry_price: Optional[float] = None
    entry_spy_price: Optional[float] = None
    status: str = "active"
    exit_week: Optional[str] = None
    exit_price: Optional[float] = None
    exit_spy_price: Optional[float] = None
    pick_return_pct: Optional[float] = None
    spy_return_pct: Optional[float] = None
    beat_spy: Optional[bool] = None
    price_timestamp: Optional[str] = None


class PerformanceSnapshotDoc(BaseModel):
    """Schema for a weekly performance-snapshot document in the ``performance`` collection."""

    week: str
    total_picks: int
    active_picks: int
    closed_picks: int
    win_rate: Optional[float] = None
    avg_return_pct: Optional[float] = None
    avg_spy_return_pct: Optional[float] = None
    beats_spy_rate: Optional[float] = None


class ChunkDoc(BaseModel):
    """Schema for an EDGAR text chunk in the ``chunks`` collection."""

    ticker: str
    filing_type: str
    filing_date: str
    chunk_index: int
    text: str
    embedding: list[float] = Field(default_factory=list)
    token_count: Optional[int] = None


class EvalDoc(BaseModel):
    """Schema for a monthly eval output document in the ``eval`` collection."""

    year: int
    month: int
    overall_accuracy: Optional[float] = None
    bull_accuracy: Optional[float] = None
    bear_accuracy: Optional[float] = None
    high_confidence_accuracy: Optional[float] = None
    medium_confidence_accuracy: Optional[float] = None
    low_confidence_accuracy: Optional[float] = None
    disclosure_citation_rate: Optional[float] = None
    feedback_summary: Optional[str] = None


class EventDoc(BaseModel):
    """Schema for a pipeline lifecycle event in the ``events`` collection."""

    event_type: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    payload: dict = Field(default_factory=dict)
