"""
screener/lib/storage/schema.py — Collection constants, doc-ID builders, and
Pydantic document schemas for the multi-agent stock screener.

Collection layout (mirrors the private reference implementation):

    tickers/     — per-ticker signal data (stock-screener_ticker_signals in the private project)
    memory/      — per-ticker episodic memory for the Judge feedback loop (ticker_memory)
    picks/       — weekly screener top-N snapshots (screener_picks)
    performance/ — weekly P&L snapshots and pick ledger (screener_performance, pick_ledger)
    chunks/      — EDGAR 10-K/10-Q text chunks with vector embeddings (disclosure_chunks)
    eval/        — monthly eval output (evals_output)
    events/      — pipeline lifecycle events (screener_events)

Doc ID conventions follow the reference project:
    - screening_{YYYYMMDD}         → tickers
    - picks_{YYYYWW}               → picks
    - perf_{YYYYWW}                → performance snapshots
    - {TICKER}_{YYYYWW}            → pick ledger entries
    - {TICKER_SLUG}                → memory docs (one per ticker, uppercase symbol)
    - chunk_{TICKER_SLUG}_{IDX}    → EDGAR chunks
    - eval_{YYYYMM}                → eval docs
    - event_{UUID}                 → event docs (auto-generated by Firestore)
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Collection name constants
# ---------------------------------------------------------------------------

TICKERS: str = "tickers"
MEMORY: str = "memory"
PICKS: str = "picks"
PERFORMANCE: str = "performance"
CHUNKS: str = "chunks"
EVAL: str = "eval"
EVENTS: str = "events"


# ---------------------------------------------------------------------------
# Doc ID helper functions
# ---------------------------------------------------------------------------


def ticker_to_slug(ticker: str) -> str:
    """Canonical slug used in Firestore doc IDs.

    Lower-cases the ticker and replaces ``-`` and ``.`` with ``_`` so that
    symbols like ``BRK.B`` and ``BF-B`` produce valid, predictable IDs.

    Examples::

        ticker_to_slug("AAPL")   → "aapl"
        ticker_to_slug("BRK.B")  → "brk_b"
        ticker_to_slug("BF-B")   → "bf_b"
    """
    return ticker.lower().replace("-", "_").replace(".", "_")


def screening_doc_id(date_str: str) -> str:
    """Doc ID for a daily ticker-signals snapshot.

    Args:
        date_str: ISO date string, e.g. ``"2026-04-29"``.

    Returns:
        e.g. ``"screening_20260429"``
    """
    return f"screening_{date_str.replace('-', '')}"


def picks_doc_id(week_id: str) -> str:
    """Doc ID for a weekly picks snapshot.

    Args:
        week_id: ISO week string, e.g. ``"202618"``.

    Returns:
        e.g. ``"picks_202618"``
    """
    return f"picks_{week_id}"


def perf_snapshot_doc_id(week_id: str) -> str:
    """Doc ID for a weekly performance snapshot.

    Args:
        week_id: ISO week string, e.g. ``"202618"``.

    Returns:
        e.g. ``"perf_202618"``
    """
    return f"perf_{week_id}"


def pick_ledger_doc_id(ticker: str, week_id: str) -> str:
    """Doc ID for an individual pick-ledger entry.

    Args:
        ticker: Upper-case ticker symbol, e.g. ``"AAPL"``.
        week_id: ISO week string, e.g. ``"202618"``.

    Returns:
        e.g. ``"AAPL_202618"``
    """
    return f"{ticker.upper()}_{week_id}"


def memory_doc_id(ticker: str) -> str:
    """Doc ID for a ticker's episodic memory record.

    One document per ticker, keyed by upper-case symbol.

    Args:
        ticker: Ticker symbol (any case).

    Returns:
        e.g. ``"AAPL"``
    """
    return ticker.upper()


def chunk_doc_id(ticker: str, index: int) -> str:
    """Doc ID for an EDGAR text chunk.

    Args:
        ticker: Ticker symbol (any case).
        index: Zero-based chunk index within the filing.

    Returns:
        e.g. ``"aapl_42"``
    """
    return f"{ticker_to_slug(ticker)}_{index}"


def eval_doc_id(year: int, month: int) -> str:
    """Doc ID for a monthly eval output document.

    Args:
        year: Four-digit year.
        month: Month number (1–12).

    Returns:
        e.g. ``"eval_202604"``
    """
    return f"eval_{year:04d}{month:02d}"


def current_week_id(dt: datetime | None = None) -> str:
    """Return the ISO week ID string for a datetime, e.g. ``"202618"``.

    Args:
        dt: Datetime to use; defaults to ``datetime.now(timezone.utc)``.
    """
    if dt is None:
        dt = datetime.now(timezone.utc)
    return dt.strftime("%G%V")


def current_quarter_id(dt: datetime | None = None) -> str:
    """Return the quarter ID string for a datetime, e.g. ``"2026Q2"``.

    Args:
        dt: Datetime to use; defaults to ``datetime.now(timezone.utc)``.
    """
    if dt is None:
        dt = datetime.now(timezone.utc)
    q = (dt.month - 1) // 3 + 1
    return f"{dt.year}Q{q}"


# ---------------------------------------------------------------------------
# Pydantic document schemas
# ---------------------------------------------------------------------------


class TickerSignalDoc(BaseModel):
    """Schema for a document in the ``tickers`` collection.

    Stores the most recent composite signal data for a single ticker.
    """

    symbol: str
    screening_date: str
    technical: float
    earnings: float
    fcf: float
    ebitda: float
    composite_score: float
    sector: str
    price: Optional[float] = None
    above_ma200: Optional[bool] = None


class ScoringWeights(BaseModel):
    bull_weight: float = 0.5
    bear_weight: float = 0.5
    sample_size: int = 0


class WeekVerdict(BaseModel):
    action: str
    confidence: float
    horizon: Optional[str] = None
    winning_side: Optional[str] = None
    entry_price: Optional[float] = None
    direction_correct: Optional[bool] = None
    magnitude_error: Optional[float] = None
    scored_at: Optional[datetime] = None
    judge_signal_citations: list[str] = Field(default_factory=list)


class MemoryDoc(BaseModel):
    """Schema for a document in the ``memory`` collection.

    One document per ticker.  The ``weeks`` map keys are ISO week IDs
    (e.g. ``"202618"``).
    """

    ticker: str
    scoring_weights: ScoringWeights = Field(default_factory=ScoringWeights)
    weeks: dict[str, WeekVerdict] = Field(default_factory=dict)


class PickEntry(BaseModel):
    rank: int
    symbol: str
    sector: str
    entry_price: float
    score: float


class PicksDoc(BaseModel):
    """Schema for a document in the ``picks`` collection.

    Weekly snapshot of the screener's top-N selections.
    """

    date: str
    week_id: str
    picks: list[PickEntry] = Field(default_factory=list)


class PickLedgerDoc(BaseModel):
    """Schema for an individual pick-ledger entry in the ``performance`` collection."""

    ticker: str
    entry_week: str
    entry_price: Optional[float] = None
    entry_spy_price: Optional[float] = None
    status: str = "active"
    exit_week: Optional[str] = None
    exit_price: Optional[float] = None
    exit_spy_price: Optional[float] = None
    pick_return_pct: Optional[float] = None
    spy_return_pct: Optional[float] = None
    beat_spy: Optional[bool] = None
    price_timestamp: Optional[str] = None


class PerformanceSnapshotDoc(BaseModel):
    """Schema for a weekly performance-snapshot document in the ``performance`` collection."""

    week: str
    total_picks: int
    active_picks: int
    closed_picks: int
    win_rate: Optional[float] = None
    avg_return_pct: Optional[float] = None
    avg_spy_return_pct: Optional[float] = None
    beats_spy_rate: Optional[float] = None


class ChunkDoc(BaseModel):
    """Schema for an EDGAR text chunk in the ``chunks`` collection."""

    ticker: str
    filing_type: str
    filing_date: str
    chunk_index: int
    text: str
    embedding: list[float] = Field(default_factory=list)
    token_count: Optional[int] = None


class EvalDoc(BaseModel):
    """Schema for a monthly eval output document in the ``eval`` collection."""

    year: int
    month: int
    overall_accuracy: Optional[float] = None
    bull_accuracy: Optional[float] = None
    bear_accuracy: Optional[float] = None
    high_confidence_accuracy: Optional[float] = None
    medium_confidence_accuracy: Optional[float] = None
    low_confidence_accuracy: Optional[float] = None
    disclosure_citation_rate: Optional[float] = None
    feedback_summary: Optional[str] = None


class EventDoc(BaseModel):
    """Schema for a pipeline lifecycle event in the ``events`` collection."""

    event_type: str
    created_at: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    payload: dict = Field(default_factory=dict)
